# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 

name: CI with install

on:
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: openmc/openmc:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package and dependencies
        run: |
          python setup.py install

      - name: install packages for tests
        run: |
          pip install -r requirements-test.txt 

      - name: Run test_utils
        run: |
          pytest tests/ -v --cov=spectrum_plotter --cov-append --cov-report term --cov-report xml

      - name: Run examples
        run: |
          cd examples
          python create_statepoint_file_for_testing.py --batches 2 --particles 100
          python spectra_matplotlib_from_tally.py
          python spectra_matplotlib_from_values.py
          python spectra_plotly_from_values.py
          python spectrum_matplotlib_from_tally.py
          python spectrum_matplotlib_from_values.py
          python spectrum_plotly_from_values.py

      - name: Upload to codecov
        uses: codecov/codecov-action@v2
