# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 

name: CI with install

on:
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:4.9.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package and dependencies
        run: |
          conda install -c conda-forge h5py=3.2.1
          conda install -c conda-forge moab
          conda install -c conda-forge openmc
          python setup.py install

      - name: install packages for tests
        run: |
          pip install -r requirements-test.txt 

      - name: Run test_utils
        run: |
          pytest tests/ -v --cov=spectrum_plotter --cov-append --cov-report term --cov-report xml

      - name: Run examples
        run: |
          cd examples
          python create_statepoint_file_for_testing.py --batches 2 --particles 100
          python examples/spectra_matplotlib_from_tally.py
          python examples/spectra_matplotlib_from_values.py
          python examples/spectra_plotly_from_values.py
          python examples/spectrum_matplotlib_from_tally.py
          python examples/spectrum_matplotlib_from_values.py
          python examples/spectrum_plotly_from_values.py

      - name: Upload to codecov
        uses: codecov/codecov-action@v2
