# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 

name: CI with install

on:
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:4.9.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package
        run: |
          python setup.py install

      - name: Run test_utils
        run: |
          pytest tests/ -v --cov=spectrum_plotter --cov-append --cov-report term --cov-report xml

      - name: Upload to codecov
        uses: codecov/codecov-action@v2
